### ISSUE TITLE
'Invalid Input'

### ISSUE THREAD

**Issue by sidan5** [StephanGeorg/staticmaps#90]
I get this error when running the example on "save" line:

    node_modules/staticmaps/node_modules/sharp/lib/constructor.js:166
    throw new Error('Invalid input');

Full code:

    const StaticMaps  = require("staticmaps");

    const mapoptions = {
	width: 600,
	height: 400
    };
    const map = new StaticMaps(mapoptions);
    
    const zoom = 13;
    const center = [13.437524,52.4945528];
    
    map.render(center, zoom);
    map.image.save('center.png');

Full error log:

    Error: Invalid input
    at Sharp (.../node_modules/staticmaps/node_modules/sharp/lib/constructor.js:166:11)
    at Image._callee3$ (.../node_modules/staticmaps/dist/image.js:230:71)
    at tryCatch (.../node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (.../node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
    at Generator.next (.../node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (.../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (.../node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at .../node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Image.<anonymous> (/.../node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)

**Comment by joan-teriihoania** [comment]
The `map.render()` method returns a Promise, since rendering the map is handled asynchronously. Therefore, you need to wait for the rendering to finish to have anything to save (no rendering, no image to save).

Add an `await` for the `map.render` call and it should be fixed.
